
name: 'Diffusion Eqn'

# ; Values
dt: 0.01
dx: 0.1
blocks: [0,1,2,3,4,5,6,7,8,9,10] 
# ; Network Parameters
kernel_size: 5
max_diff_order: 2
acc_order: 2
n_hidden_layers: 2

# ; Data
dataname: 'Diffusion'
viscosity: 0.1
batch_size: 32
channel_names: 'u'
data_timescheme: 'rk4'
data_dir: '/sdsd/dsds/sdsd'
Nt: 100
Nx: 32
sigma: 1

# ; Others 

sparsity: 0.05
epochs: 500
results_dir: '/comet/results/'
seed: -1
learning_rate: 0.005